name: "Install yq"

description: "Downloads and installs yq"

runs:
  using: "composite"
  steps:
    - name: "📦 Install yq"
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
      shell: bash
