/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSocialRouteImport } from './routes/_layout/social'
import { Route as LayoutGraphRouteImport } from './routes/_layout/graph'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSocialRoute = LayoutSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGraphRoute = LayoutGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/graph': typeof LayoutGraphRoute
  '/social': typeof LayoutSocialRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/graph': typeof LayoutGraphRoute
  '/social': typeof LayoutSocialRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/graph': typeof LayoutGraphRoute
  '/_layout/social': typeof LayoutSocialRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/graph' | '/social' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/graph' | '/social' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/graph'
    | '/_layout/social'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/social': {
      id: '/_layout/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof LayoutSocialRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/graph': {
      id: '/_layout/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof LayoutGraphRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutGraphRoute: typeof LayoutGraphRoute
  LayoutSocialRoute: typeof LayoutSocialRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutGraphRoute: LayoutGraphRoute,
  LayoutSocialRoute: LayoutSocialRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
